### ISSUE TITLE
Hi,I had the same problem as you,need some help

### ISSUE THREAD

**Issue by yangyangwuwu** [bhuebner3/Recommender-System-LightGBM#1]
Hi,I had the same problem as you, then followed the steps in this comment and modified it, but it still doesn't work, may I ask how did you finally modify it to solve the problem?
![Snipaste_2023-03-13_16-32-48](https://user-images.githubusercontent.com/92963445/224648936-8150e045-efc6-4205-b470-bd725fa98e58.png)

**Comment by bhuebner3** [comment]
I followed his suggestion here:

https://github.com/TangJiakai/RecBole-FairRec/issues/3#issuecomment-1382621051
